# Generated by Django 5.2.7 on 2025-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('universidad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comision', models.IntegerField(unique=True)),
                ('code', models.CharField(default='0f2e36b9794448fdb56526911080f422', max_length=32, unique=True)),
            ],
        ),
    ]
