# Generated by Django 5.2.7 on 2025-11-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='ef24924f2e73477e8095925e7fe5054d', max_length=32, unique=True),
        ),
    ]
