# Generated by Django 5.2.7 on 2025-11-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='9e916a22389f4c52b52a33bfaebfac7b', max_length=32, unique=True),
        ),
    ]
