# Generated by Django 5.2.7 on 2025-11-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='c8d51c1e37cf42e5ac81839efb86202d', max_length=32, unique=True),
        ),
    ]
