# Generated by Django 5.2.7 on 2025-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='eea5df6cb35548f0b4521014863147b5', max_length=32, unique=True),
        ),
    ]
