# Generated by Django 5.2.7 on 2025-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='6ecbfd5ef5e541618674a1e08cd20b18', max_length=32, unique=True),
        ),
    ]
