# Generated by Django 5.2.7 on 2025-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='bc385ed30d1641ee995cf50fbffede29', max_length=32, unique=True),
        ),
    ]
