# Generated by Django 5.2.7 on 2025-11-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='2d7f3abda6494bb8858ca77b7e17a4e8', max_length=32, unique=True),
        ),
    ]
