# Generated by Django 5.2.7 on 2025-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='7f01334918894462b21d514f3b832078', max_length=32, unique=True),
        ),
    ]
