# Generated by Django 5.2.7 on 2025-11-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='c18e18fa50a04eaa8ea23dbd797b371b', max_length=32, unique=True),
        ),
    ]
