# Generated by Django 5.2.7 on 2025-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='a946acdc65924a73992d1c22242ea2b9', max_length=32, unique=True),
        ),
    ]
