# Generated by Django 5.2.7 on 2025-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_curso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.CharField(default='ab13ba0b6f144879b2d5a897e3d6a275', max_length=32, unique=True),
        ),
    ]
