# Generated by Django 5.2.7 on 2025-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=30)),
                ('apellidoC', models.CharField(max_length=30)),
                ('emailC', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='T_comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroC', models.IntegerField()),
                ('mesaC', models.IntegerField()),
                ('localC', models.IntegerField()),
                ('estadoC', models.CharField(max_length=15)),
                ('totalcomanda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=40)),
                ('totalmesas', models.IntegerField()),
                ('totalempleados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM', models.CharField(max_length=30)),
                ('apellidoM', models.CharField(max_length=30)),
                ('emailM', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
