# Generated by Django 5.2.7 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPostulante', models.CharField(max_length=30)),
                ('nombreC', models.CharField(max_length=30)),
                ('apellidoC', models.CharField(max_length=30)),
                ('emailC', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='T_Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEntrevista', models.IntegerField(unique=True)),
                ('idProcesoE', models.IntegerField()),
                ('idPostulanteE', models.CharField(max_length=30)),
                ('fechaE', models.DateField()),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalpuestos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='T_Cliente',
        ),
        migrations.DeleteModel(
            name='T_comanda',
        ),
        migrations.DeleteModel(
            name='T_Local',
        ),
        migrations.DeleteModel(
            name='T_mesero',
        ),
    ]
